using UnityEngine;
using System.Collections;

public class PlayerController : MonoBehaviour
{
    public float speed = 2.0f; // the movement speed of the player
    private Rigidbody2D rb;
    private Vector2 movementDirection;
    private bool isOnStairs = false; // when on stairs, the player moves in a different angle.
    public bool isCrouching = false; // when crouching, the player moves slower
    private SpriteRenderer spriteRenderer;
    private float lastAngle;  // Store the last calculated angle
    private bool isRunning = false;

    // Archer specifics
    public bool isActive; // If the character is active
    public bool isRanged; // If the character is an archer OR caster character
    public bool isStealth; // If true, Makes the player transparent when crouched
    public GameObject projectilePrefab; // prefab to the projectile
    public GameObject AoEPrefab;
    public GameObject Special1Prefab;
    public GameObject HookPrefab; // Certain characters might have a grappling hook

    public float projectileSpeed = 10.0f; // Speed at which the projectile travels
    public float shootDelay = 0.5f; // Delay in seconds before the projectile is fired

    // Melee specifics
    public bool isMelee; // If the character is a melee character
    public GameObject meleePrefab; // prefab for the melee attack



    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        spriteRenderer = GetComponent<SpriteRenderer>(); // Get the SpriteRenderer component

    }

    void Update()
    {

        // WASD movement (standard 2D movement)
        float moveX = 0f;
        float moveY = 0f;
        if (Input.GetKey(KeyCode.W)) moveY += 1f;
        if (Input.GetKey(KeyCode.S)) moveY -= 1f;
        if (Input.GetKey(KeyCode.A)) moveX -= 1f;
        if (Input.GetKey(KeyCode.D)) moveX += 1f;
        movementDirection = new Vector2(moveX, moveY).normalized;

        // Check if movement keys are pressed
        bool isMoving = movementDirection != Vector2.zero;
        isRunning = isMoving;

        if (Input.GetKeyDown(KeyCode.C))
        {
            HandleCrouching();
        }

        if (isActive)
        {
            if (isRanged)
            {
                if (Input.GetMouseButtonDown(1))
                {
                    Invoke(nameof(DelayedShoot), shootDelay);

                }

                if (Input.GetKeyDown(KeyCode.Alpha1))
                {
                    StartCoroutine(DeploySpecial1Delayed());

                }

                if (Input.GetKeyDown(KeyCode.Alpha3))
                {
                    StartCoroutine(DeployAoEDelayed());

                }

                if (Input.GetKeyDown(KeyCode.Alpha5))
                {
                    StartCoroutine(Quickshot());

                }
                if (Input.GetKeyDown(KeyCode.Alpha6))
                {
                    StartCoroutine(CircleShot());

                }
            }

            if (isMelee)
            {
                if (Input.GetKeyDown(KeyCode.Alpha1))
                {
                    StartCoroutine(DeployAoEDelayed());

                }


                if (Input.GetKeyDown(KeyCode.Alpha5))
                {
                    StartCoroutine(DeployHookDelayed());

                }
                if (Input.GetKeyDown(KeyCode.Alpha6))
                {
                    Invoke(nameof(DelayedShoot), shootDelay);

                }
            }
        }
    }


    void FixedUpdate()
    {
        if (movementDirection != Vector2.zero)
        {
            rb.MovePosition(rb.position + movementDirection * speed * Time.fixedDeltaTime);
        }
    }




    float SnapAngleToEightDirections(float angle)
    {
        angle = (angle + 360) % 360;

        if (isOnStairs)
        {
            // Angle adjustments when on stairs
            if (angle < 30 || angle >= 330)
                return 0;
            else if (angle >= 30 && angle < 75)
                return 60;
            else if (angle >= 75 && angle < 105)
                return 90;
            else if (angle >= 105 && angle < 150)
                return 120;
            else if (angle >= 150 && angle < 210)
                return 180;
            else if (angle >= 210 && angle < 255)
                return 240;
            else if (angle >= 255 && angle < 285)
                return 270;
            else if (angle >= 285 && angle < 330)
                return 300;
        }
        else
        {
            // Normal angle adjustments
            if (angle < 15 || angle >= 345)
                return 0; // East (isEast)
            else if (angle >= 15 && angle < 60)
                return 35; // Northeast (isNorthEast)
            else if (angle >= 60 && angle < 120)
                return 90; // North (isNorth)
            else if (angle >= 120 && angle < 165)
                return 145; // Northwest (isNorthWest)
            else if (angle >= 165 && angle < 195)
                return 180; // West (isWest)
            else if (angle >= 195 && angle < 240)
                return 215; // Southwest (isSouthWest)
            else if (angle >= 240 && angle < 300)
                return 270; // South (isSouth)
            else if (angle >= 300 && angle < 345)
                return 330; // Southeast (isSouthEast)

        }

        return 0;
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.tag == "Stairs")
        {
            isOnStairs = true;
        }
    }

    private void OnTriggerExit2D(Collider2D other)
    {
        if (other.tag == "Stairs")
        {
            isOnStairs = false;
        }
    }

    float GetPerpendicularAngle(float angle, bool isLeft)
    {
        // Calculate the base perpendicular angle (90 degrees offset)
        float perpendicularAngle = isLeft ? angle - 90 : angle + 90;
        perpendicularAngle = (perpendicularAngle + 360) % 360; // Normalize the angle

        // Use your SnapAngleToEightDirections function to snap to the nearest valid angle
        return SnapAngleToEightDirections(perpendicularAngle);
    }

    void HandleMovement()
    {
        // No longer needed; movement is handled directly in Update()
    }

    void HandleCrouching()
    {
        if (Input.GetKeyDown(KeyCode.C))
        {
            isCrouching = !isCrouching; // Toggle crouching
                                        // speed = isCrouching ? 1.0f : 2.0f; // Adjust speed based on crouch state if needed

            if (isCrouching && isStealth)
            {
                // Set the color to dark gray and reduce opacity to 50%
                spriteRenderer.color = new Color(0.5f, 0.5f, 0.5f, 0.5f);
            }
            else
            {
                // Reset the color to white and opacity to 100%
                spriteRenderer.color = Color.white;
            }
        }
    }

    //Ranged character specific methods:

    public void SetArcherStatus(bool status)
    {
        isRanged = status;
    }

    public void SetActiveStatus(bool status)
    {
        isActive = status;
    }

    void DelayedShoot()
    {
        Vector2 fireDirection = new Vector2(Mathf.Cos(lastAngle * Mathf.Deg2Rad), Mathf.Sin(lastAngle * Mathf.Deg2Rad));
        ShootProjectile(fireDirection);
    }

    void ShootProjectile(Vector2 direction)
    {
        float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg;
        GameObject projectileInstance = Instantiate(projectilePrefab, transform.position, Quaternion.Euler(0, 0, angle));
        Rigidbody2D rbProjectile = projectileInstance.GetComponent<Rigidbody2D>();
        if (rbProjectile != null)
        {
            rbProjectile.velocity = direction * projectileSpeed;
        }
        // Destroy the instantiated prefab after another 1.5 seconds
        Destroy(projectileInstance, 1.5f);
    }

    IEnumerator Quickshot()
    {
        // Initial small delay before starting the quickshot sequence
        yield return new WaitForSeconds(0.1f);

        // Loop to fire five projectiles in the facing direction
        for (int i = 0; i < 5; i++)
        {
            Vector2 fireDirection = new Vector2(Mathf.Cos(lastAngle * Mathf.Deg2Rad), Mathf.Sin(lastAngle * Mathf.Deg2Rad));
            ShootProjectile(fireDirection);

            // Wait for 0.18 seconds before firing the next projectile
            yield return new WaitForSeconds(0.18f);
        }
    }

    IEnumerator CircleShot()
    {
        float initialDelay = 0.1f;
        float timeBetweenShots = 0.9f / 8;  // Total time divided by the number of shots

        yield return new WaitForSeconds(initialDelay);

        // Use the lastAngle as the start angle and generate projectiles in 8 directions
        for (int i = 0; i < 8; i++)
        {
            float angle = lastAngle + i * 45;  // Increment by 45 degrees for each direction
            angle = Mathf.Deg2Rad * angle;  // Convert to radians for direction calculation
            Vector2 fireDirection = new Vector2(Mathf.Cos(angle), Mathf.Sin(angle));
            ShootProjectile(fireDirection);

            yield return new WaitForSeconds(timeBetweenShots);
        }
    }

    IEnumerator DeployAoEDelayed()
    {
        if (AoEPrefab != null)
        {
            if (isMelee)
            {
                yield return new WaitForSeconds(0.5f);
            }
            // Wait for 0.3 seconds before instantiating the AoEPrefab
            else
            {
                yield return new WaitForSeconds(0.3f);
            }
            // Instantiate the AoE prefab at the player's position
            GameObject aoeInstance = Instantiate(AoEPrefab, transform.position, Quaternion.identity);

            // Destroy the instantiated prefab after another 0.5 seconds
            Destroy(aoeInstance, 0.9f);
        }
    }

    IEnumerator DeploySpecial1Delayed()
    {
        if (Special1Prefab != null)
        {
            if (isMelee)
            {
                yield return new WaitForSeconds(0.5f);
            }
            // Wait for 0.6 seconds before instantiating the Special1Prefab
            else
            {
                yield return new WaitForSeconds(0.6f);
            }
            // Instantiate the AoE prefab at the player's position
            GameObject Special1PrefabInstance = Instantiate(Special1Prefab, transform.position, Quaternion.identity);

            // Destroy the instantiated prefab after another 0.5 seconds
            Destroy(Special1PrefabInstance, 1.0f);
        }
    }
    IEnumerator DeployHookDelayed()
    {
        if (HookPrefab != null)
        {
            Vector2 direction = new Vector2(Mathf.Cos(lastAngle * Mathf.Deg2Rad), Mathf.Sin(lastAngle * Mathf.Deg2Rad));
            float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg;
            GameObject hookInstance = Instantiate(HookPrefab, transform.position, Quaternion.Euler(0, 0, angle));
            // Destroy the instantiated prefab after another 1.0 seconds
            Destroy(hookInstance, 1.0f);
        }
        yield return null; // Ensures the method correctly implements IEnumerator
    }


}
